apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hi-tap
  namespace: dev-tap
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hi-tap
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: "https://gitea.tap.bmath.nyc/bmath.nyc/hi-tap.git"
    subPath: hi-tap
  serviceClaims:
    - name: hi-tap
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: hi-tap-registration-claim
